# Generated by Django 5.2.2 on 2025-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionAnalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajes', models.JSONField()),
                ('sentimiento', models.CharField(max_length=12)),
                ('intencion_compra', models.CharField(max_length=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
