# Generated by Django 5.2.2 on 2025-06-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionanalizada',
            name='urgencia',
            field=models.CharField(default='Media', max_length=8),
        ),
    ]
