# Generated by Django 5.2.2 on 2025-06-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_conversacionanalizada_urgencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionanalizada',
            name='id_context',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
